name: Run summmarization-parallel
env:
    WATSONX_KEY: ${{secrets.WATSONX_KEY}}
    WATSONX_PROJECT_ID: ${{secrets.WATSONX_PROJECT_ID}}
    WATSONX_URL: ${{secrets.WATSONX_URL}}
on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0,2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r cncf-youtube-channel-summarizer/requirements.txt

    - name: Run script for iteration
      run: |
          start=${{ matrix.index }}
          end=$((start + 1))
          echo "Running script with arguments: $start, $end"
          python cncf-youtube-channel-summarizer/transcript_summarizer_parallel.py $start $end

    - name: Upload Summaries
      uses: actions/upload-artifact@v4
      with:
          name: cncf_video_summary_${{ matrix.index }}_${{ matrix.index_plus_one }}.csv
          path: cncf-youtube-channel-summarizer/data/cncf_video_summary_${{ matrix.index}}.csv

    - name: Upload missed_video_id 
      uses: actions/upload-artifact@v4
      with:
          name: missed_video_id_${{ matrix.index }}_${{ matrix.index_plus_one }}.txt
          path: cncf-youtube-channel-summarizer/data/missed_video_id_${{ matrix.index}}.txt

    - name: Commit Change for "cncf_video_summary.csv"
      run: |
          git config --global user.name 'Yuhao Chen'
          git config --global user.email 'yuhao.chenyh@gmail.com'
          git add cncf-youtube-channel-summarizer/data/cncf_video_summary_${{matrix.index}}.csv || exit 0
          git commit -m "Add Summaries and Keywords" --signoff || exit 0
          git push


    - name: Commit Change for "missed_video_id.txt"
      run: |
          git config --global user.name 'Yuhao Chen'
          git config --global user.email 'yuhao.chenyh@gmail.com'
          git add cncf-youtube-channel-summarizer/data/missed_video_id_${{matrix.index}}.txt || exit 0
          git commit -m "Add missed_video_id" --signoff || exit 0
          git push
