name: Run transcripts-summarization Pipline
env:
    WATSONX_KEY: ${{secrets.WATSONX_KEY}}
    WATSONX_PROJECT_ID: ${{secrets.WATSONX_PROJECT_ID}}
    WATSONX_URL: ${{secrets.WATSONX_URL}}
on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r cncf-youtube-channel-summarizer/requirements.txt

    - name: Do Summarization by LLM
      run: | 
           python cncf-youtube-channel-summarizer/transcript_summarizer.py  

    - name: Upload transcript
      uses: actions/upload-artifact@v4
      with:
        name: CNCF_video_information.json
        path: cncf-youtube-channel-summarizer/data/cncf_video_summary.json

    - name: Commit Change for "cncf_video_summary.csv"
      run: |
          git config --global user.email "dependabot[bot]@users.noreply.github.com" 
          git config --global user.name "dependabot[bot]"
          git add cncf-youtube-channel-summarizer/data/cncf_video_summary.csv || exit 0
          git commit -m "Add Summaries and Keywords" --signoff || exit 0
          git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Commit Change for "missed_video_id.txt"
      run: |
          git config --global user.email "dependabot[bot]@users.noreply.github.com" 
          git config --global user.name "dependabot[bot]"
          git add cncf-youtube-channel-summarizer/data/missed_video_id.txt || exit 0
          git commit -m "Add missed_video_id" --signoff || exit 0
          git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
